### ISSUE TITLE
Any plans for a API documentation?

### ISSUE THREAD

**Issue by atilacamurca** [ForbesLindesay/taxi-rank#11]
Any plans for a API documentation?

Based on what I already use, [NightWatch](http://nightwatchjs.org/), it would be great to see something like their API reference (<http://nightwatchjs.org/api>), describing the methods and giving some examples.

**Comment by ForbesLindesay** [comment]
What specific documentation do you feel is lacking?

**Comment by ForbesLindesay** [comment]
The way you use this project is nothing like nightwatch.  You use a webdriver client, e.g. Night Watch.

## Step 1 - run taxi-rank

Install taxi-rank with:

```
npm install -g taxi-rank
```

Then in a separate terminal to where you are running your webdriver client, run:

```
taxi-rank
```

## Step 2 - configure your wedriver client of choice

For Nightwatch, you can just set your selenium_port to `9516`.

You can also use cabbiejs by simply using:

```js
import cabbie from 'cabbie-sync';

const driver = cabbie('taxirank', {debug: true});

// use the driver here
```

The API for the cabbie driver is at https://cabbiejs.org/api/classes/driver/

I haven't documented the API for the client, since you can use your client of choice.
